# Configuración para Base de Datos en Memoria (H2)
spring.datasource.url=jdbc:h2:mem:literaturadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto permite que Hibernate cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Opcional: Para ver qué consultas hace la IA en la consola
spring.jpa.show-sql=true

# Habilitar la consola de H2 en el navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true